[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/proxy.js"
  to = "https://simpleanalyticsexternal.com/proxy.js?hostname=fleethive.ai&path=/simple"
  status = 200

[[redirects]]
  from = "/auto-events.js"
  to = "https://scripts.simpleanalyticscdn.com/auto-events.js"
  status = 200

[[redirects]]
  from = "/simple/*"
  to = "https://queue.simpleanalyticscdn.com/:splat"
  status = 200
